-------------------------------------------------------------------------------
Test set: org.dalvarez.shop.core.domain.shared.validation.IntegerInRangeValidatorShouldTestCase
-------------------------------------------------------------------------------
Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in org.dalvarez.shop.core.domain.shared.validation.IntegerInRangeValidatorShouldTestCase
shouldNotPassValidationCauseIsLower  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <Field <?=0> has not passed the validator <InRangeValidator> cause the value is out of range [<minValue=%.2f>, <maxValue=%.2f>]> but was: <Field <?=0> has not passed the validator <InRangeValidator> cause the value is out of range [<minValue=100.00>, <maxValue=1000.00>]>
	at org.dalvarez.shop.core.domain.shared.validation.IntegerInRangeValidatorShouldTestCase.shouldNotPassValidationCauseIsLower(IntegerInRangeValidatorShouldTestCase.java:26)

shouldNotPassValidationCauseIsHigher  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <Field <?=1001> has not passed the validator <InRangeValidator> cause the value is out of range [<minValue=%.2f>, <maxValue=%.2f>]> but was: <Field <?=1001> has not passed the validator <InRangeValidator> cause the value is out of range [<minValue=100.00>, <maxValue=1000.00>]>
	at org.dalvarez.shop.core.domain.shared.validation.IntegerInRangeValidatorShouldTestCase.shouldNotPassValidationCauseIsHigher(IntegerInRangeValidatorShouldTestCase.java:33)

